### ISSUE TITLE
Error downloading thatevilone

### ISSUE THREAD

**Issue by joebywan** [cwoac/thingy_grabber#10]
Not sure what's occurring here.  It creates the folder "3389073 - only in death".  Nothing is in it though.

Downloading thing 27 - 3389073
Looking for old dir at ./stls/thatevilone designs\only in death...
Traceback (most recent call last):
  File "D:\waste\thingygrabber\thingy_grabber.py", line 660, in <module>
    main()
  File "D:\waste\thingygrabber\thingy_grabber.py", line 646, in main
    Designs(user, args.directory, args.quick).download()
  File "D:\waste\thingygrabber\thingy_grabber.py", line 240, in download
    RC = Thing(thing).download(self.download_dir)
  File "D:\waste\thingygrabber\thingy_grabber.py", line 451, in download
    with open(filelist_file, 'w', encoding="utf-8") as fl_handle:
FileNotFoundError: [Errno 2] No such file or directory: './stls/thatevilone desi
gns\\3389073 - only in death...\\filelist.txt'

I know I've been posting a ton of issues, this is the only one it tripped up on now after that last update.  It's not eating all of my ram too :)  Thanks for your help.

**Comment by cwoac** [comment]
Huh, weird, it works for me.

**Comment by joebywan** [comment]
Does it generate the same foldername for that thing?

**Comment by joebywan** [comment]
Are you on win7?  I had a look further into it and the name of the thing has 3 trailing ...

When I try adding that to the folder name it disappears for a second or two and reappears without the ...

I believe it might be an issue with windows.  Could ... be added to the sanitising to remove please?

I did notice there was one or two other errors I got in my last runthrough, I'm running it through again and will paste them up for you.

**Comment by cwoac** [comment]
OK, so I've reproduced on windows 10. It's weird, as it isn't the ... character, but three seperate .s Possibly windows has issues with dir names ending in .s? Investigating.
