### ISSUE TITLE
Issue copying files on one particular thing

### ISSUE THREAD

**Issue by joebywan** [cwoac/thingy_grabber#17]
![image](https://user-images.githubusercontent.com/4845431/89361838-9efbba00-d70f-11ea-9801-e7b2d31e4a7d.png)

User maz3r.  Happens on that same thing every time.

**Comment by cwoac** [comment]
Hmmm. looks like an actual bug, I'll dig into it. Given it was in the thing update code, you could just delete / move sideways that one thing and it should be OK

**Comment by joebywan** [comment]
I tried deleting the folder and it still didn't work.  I'll run it again
and get you a copy of the error.

**Comment by cwoac** [comment]
So, I've just released a new version which should handle this error correctly- let me know if it doesn't.
