### ISSUE TITLE
Only able to download 30 items from a source

### ISSUE THREAD

**Issue by Flyingvette** [cwoac/thingy_grabber#20]
Occurred when using the 'user' parameter. Believe this is the issue:
https://www.thingiverse.com/groups/developers/forums/general/topic:30672

https://developer.github.com/v3/#pagination

Thank you for your work on this, I couldn't get other thingiverse crawlers to work at all.

**Comment by cwoac** [comment]
Hmmm. pagination _was_ working. I will look into it.

**Comment by Flyingvette** [comment]
Cool cool. Please let me know if I can help with testing or anything.

**Comment by cwoac** [comment]
Fixed by #21
